# Aliase
git config --global alias.a 'add --all'
git config --global alias.c 'commit -m'
git config --global alias.s 'status'
git config --global alias.l 'log --graph --oneline --all'
git config --global alias.ll 'log -1 HEAD'
git config --global alias.sl 'stash list'
git config --global alias.sc 'stash clear'
git config --global alias.t 'tag'
git config --global alias.b 'branch'
git config --global alias.cfg 'config --global --list'
